/*
 * libavoid-loader.js — hand-authored loader for the vendored libavoid-js WASM
 * router. NOT generated by vendor-libavoid.js (it never changes with the
 * upstream version). Runs after libavoid.min.js (defines AvoidLib) and
 * libavoid-wasm.js (defines window.__LIBAVOID_WASM_B64) in the load order.
 *
 * Decodes the inlined base64 wasm into globalThis.__LIBAVOID_WASM_BINARY (a
 * Uint8Array), which the patched Emscripten loader picks up as `wasmBinary` so
 * the module instantiates with NO fetch — required for the offline PWA and the
 * sandboxed embed (CSP forbids fetching the .wasm). Kicks off AvoidLib.load()
 * eagerly so the router is usually warm by the time the user invokes routing,
 * and parks the promise on window.__libavoidReady (resolving to the Avoid
 * namespace, or null on failure). Callers MUST await it before using Avoid —
 * AvoidLib.getInstance() throws if load() hasn't resolved. Failures degrade
 * gracefully: __libavoidReady resolves to null and routing is skipped.
 *
 * Globals match drawio-mcp's loader byte-for-byte (AvoidLib / window.Avoid /
 * window.__libavoidReady / __LIBAVOID_WASM_B64 / __LIBAVOID_WASM_BINARY) so the
 * router algorithm core stays portable between the two repos — the core is the
 * CANONICAL libavoid-routing.js next to this file (drawio-mcp vendors verbatim
 * copies under the mcp-app-server and mcp-tool-server vendor/libavoid/ dirs);
 * the editor binding is js/diagramly/LibavoidRouting.js.
 */
(function()
{
	function b64ToBytes(b64)
	{
		var bin = atob(b64);
		var bytes = new Uint8Array(bin.length);

		for (var i = 0; i < bin.length; i++)
		{
			bytes[i] = bin.charCodeAt(i);
		}

		return bytes;
	}

	if (typeof AvoidLib === 'undefined' || AvoidLib == null)
	{
		// Glue failed to load/parse; leave __libavoidReady unset so the menu
		// item hides and callers skip routing.
		if (typeof console !== 'undefined')
		{
			console.error('[libavoid] AvoidLib global missing; routing disabled');
		}

		return;
	}

	if (typeof window === 'undefined' || window.__LIBAVOID_WASM_B64 == null)
	{
		if (typeof console !== 'undefined')
		{
			console.error('[libavoid] wasm payload missing; routing disabled');
		}

		return;
	}

	try
	{
		globalThis.__LIBAVOID_WASM_BINARY = b64ToBytes(window.__LIBAVOID_WASM_B64);
	}
	catch (e)
	{
		console.error('[libavoid] base64 decode failed; routing disabled:', e);
		return;
	}

	// libavoid's stderr, routed here by the vendor-patched Emscripten factory
	// call in libavoid.min.js (printErr, injected like wasmBinary). The solver
	// prints "Warning: skipping checkpoint for connector ..." whenever it
	// discards a jetty checkpoint it cannot honour (e.g. while a drag
	// temporarily buries a pinned anchor under another shape) — harmless and
	// non-actionable, so demote those to console.debug; anything else keeps
	// the console.error default.
	globalThis.__LIBAVOID_PRINT_ERR = function(msg)
	{
		if (typeof console === 'undefined')
		{
			return;
		}

		if (/^Warning: skipping checkpoint\b/.test(msg))
		{
			if (console.debug != null)
			{
				console.debug('[libavoid]', msg);
			}
		}
		else
		{
			console.error(msg);
		}
	};

	window.__libavoidReady = AvoidLib.load().then(function()
	{
		window.Avoid = AvoidLib.getInstance();
		return window.Avoid;
	}).catch(function(e)
	{
		console.error('[libavoid] wasm load failed; routing disabled:', (e && e.message), e);
		return null;
	});
})();
