mxscript(geBasePath + '/Editor.js');
mxscript(geBasePath + '/EditorUi.js');
mxscript(geBasePath + '/Sidebar.js');
mxscript(geBasePath + '/Graph.js');
mxscript(geBasePath + '/Shapes.js');
mxscript(geBasePath + '/Actions.js');
mxscript(drawDevUrl + 'js/diagramly/sidebar/Sidebar.js');
mxscript(drawDevUrl + 'js/diagramly/DrawioFile.js');
mxscript(drawDevUrl + 'js/diagramly/LocalFile.js');
mxscript(drawDevUrl + 'js/diagramly/EditorUi.js');
mxscript(drawDevUrl + 'js/diagramly/Pages.js');
mxscript(drawDevUrl + 'js/diagramly/GraphViewer.js');
mxscript('main.js');
